name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Set Build Environment
      run: DamianReeves/write-file-action
      with:
        path: "Secrets.cs"
        contents: |
          public class Secrets { public static string ClientId => "{{ secrets.GH_PRUNE_CLIENT_ID }}"; public static string ClientSecret => "{{ GH_PRUNE_CLIENT_SECRET }}"; }
    - name: Build Windows x64
      run: dotnet publish -r win-x64 --configuration Release --self-contained true -p:PublishSingleFile=true -p:IncludeAllContentForSelfExtract=true -p:IncludeNativeLibrariesForSelfExtract=true
    - name: Build Linux x64
      run: dotnet publish -r linux-x64 --configuration Release --self-contained true -p:PublishSingleFile=true -p:IncludeAllContentForSelfExtract=true -p:IncludeNativeLibrariesForSelfExtract=true
    - name: Build OSX x64
      run: dotnet publish -r osx-x64 --configuration Release --self-contained true -p:PublishSingleFile=true -p:IncludeAllContentForSelfExtract=true -p:IncludeNativeLibrariesForSelfExtract=true
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Compiled-Packages
        path: |
          bin/Release/net5.0/**/publish
